# Generated by Django 3.1.1 on 2024-06-25 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_hod_custom_admin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hod',
            name='custom_admin_id',
        ),
    ]
